### ISSUE TITLE
move element trigger

### ISSUE THREAD

**Issue by nickygan** [Rhyzz/repeatable-fields#22]
i m not find the trigger for moving element, 
i just want to sort array when the element moving 

in your example, i can move the element but the array index not change 
Array
(
    [location] => Array
        (
            [2] => first
            [1] => second
            [0] => third
        )
)

i just want to make this

Array
(
    [location] => Array
        (
            [0] => first            
            [1] => second
            [2] => third
        )
)

where i can find the trigger, in repeatable-field.js or jquery-ui.js ???
anyway, thanks for the code :+1:

**Comment by naifamoodi** [comment]
Hi. Are you using a backend language? And why is the index important? The index is left intact and not modified because if it was modified it would interfere with new elements added. If you are using a backend language to process the fields, you can easily reset the index and get the ordering of your choice.
