### ISSUE TITLE
Can I modify this plugin to also make table columns as well as rows?

### ISSUE THREAD

**Issue by VincEnterprise** [Rhyzz/repeatable-fields#28]
I'm currently already using this plugin in my project for just rows and I love how well it works.
But this project also requires that I develop a form in which the user is able to dynamically create a table (rows and columns).

So I basically want the buttons in the table header to also be able to add and remove columns besides only making new rows. 

Ideally it would then update every row with the appropriate amount of input-fields (based on # of columns).

Would something like this be easily possible by modifying this plugin or should I look elsewhere?

**Comment by naifamoodi** [comment]
Hi, thanks but I am afraid this plugin was never designed for columns. Rather it was designed only for rows. I doubt any plugins exists out there which lets you handle both rows and columns but of course I could very well be wrong. So I would suggest you further explore and see if you can find such a plugin.

**Comment by VincEnterprise** [comment]
Thanks for your reply.

I knew that this plugin wasn't designed for handling columns, that's why I asked if there was a way to modify it so that it would be able to. Since the columns don't need to be sortable I thought the modification would be pretty easily done.

But I'm guessing it's the updating of the number of fields in each row would be the hardest part right?

**Comment by naifamoodi** [comment]
The truth is, you are better of creating a plugin from scratch. What you are after is very complex. When I had released this plugin years back, it was ahead of its time. There were no alternatives back then that is why I created this plugin for my own personal use and decided to released it to the public. It was ahead of its time and it had no alternatives back then because it was complicated. What made it complex was that you can even have nested rows with this plugin.

Now to introduce columns, this would double the complexity IMHO.

**Comment by VincEnterprise** [comment]
If it changes anything, I wouldn't need nested functionality to work, just have rows update the amount of input fields inside of it dynamically based on which button is clicked.
